// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckStatus():Promise<main.StatusResult>;

export function ExportModel(arg1:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetStartupEnabled():Promise<boolean>;

export function PrepareExport():Promise<void>;

export function PrepareOVMS():Promise<void>;

export function PullModel(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SearchModels(arg1:string,arg2:Array<string>):Promise<Array<main.HFModel>>;

export function SetStartup(arg1:boolean):Promise<void>;
